### PR TITLE
Move block models to data generators

### PR DESCRIPTION
**Pull request by vemerion**
This commit adds a data generator for block models. Also added a line to
build.gradle to make it aware of the generated resources.

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Hey, thank you got the Pr but I have however, gave up on data generator due to the mods I depend on for mod compat will blow up when I do the runData task. And one of my unrelated mixin (the material invoker) also crashes only on runData and me and many other modders couldn’t figure out why. The whole thing is a mess and isn’t worth it lol. For a mod without dependencies, yeah data gen is perfect. But in my case, getting it to run is a pain and too much effort

**Comment by TelepathicGrunt** [comment]
Actually, when you cloned this mod to do the PR, were you able to run genData task to do the json files?

**Comment by vemerion** [comment]
I did get it running after tinkering a bit with a few files, but I assumed that the problems were due to some weirdness with my setup. I'll push those changes later today!

**Comment by TelepathicGrunt** [comment]
Alright, thank! I would like to see how you got it running as that might be immensely helpful for me!

**Comment by vemerion** [comment]
I have now pushed the changes!

**Pull request merged**
