### PR TITLE
Upgrade Aquatic Revived Coral Compat

### PR DESCRIPTION
**Pull request by Cicopath**
title. Tested via datapack and everything appears to be working correctly!

There is one unique coral: Prismarine Coral. when left out to dry, it turns into Elder Prismarine Coral (including the decoration variants). therefore, I added revival recipes for this one too

### CODE REVIEW

**Comment by Cicopath** [comment]
Ah, I didn't realize that the dead coral items should be added to a random disallowed trade tag. do you want me to do that?

**Comment by TelepathicGrunt** [comment]
Any revival item should also be put into the disallowed bonus trade tag so the item does not get duplicated. Bonus trades are 3x the reward but revival trades are more of giving an item to restore back to original living state. Doesn’t make sense to multiply

**Comment by Cicopath** [comment]
Alright! Just need to edit one more tag. The Prismarine corals are not being registered in the sugar water loggable tag.

**Comment by Cicopath** [comment]
I noticed that the dead corals, even though they have a waterlogged boolean property, aren't included in the `the_bumblezone:sugar_water/waterloggable_blocks_when_placed_in_fluid` block tag. I also don't see any other modded tags. I added _just_ the Prismarine Coral block tag for consistency sake, but I don't want to be accidentally messing with tags that I shouldn't be

image

**Review by TelepathicGrunt — APPROVED** [review]

**Comment by TelepathicGrunt** [comment]
> I noticed that the dead corals, even though they have a waterlogged boolean property, aren't included in the the_bumblezone:sugar_water/waterloggable_blocks_when_placed_in_fluid block tag. 

The `#minecraft:wall_corals` entry and `#minecraft:corals` should already be handling dead corals. Are upgrade aquatics coral already in these tags? if so, then upgrade aquatics does not need direct entries in the waterloggable tag

**Pull request merged**
