### PR TITLE
Add option for disabling Phantom spawns.

### PR DESCRIPTION
**Pull request by wtchappell**
Hi there!

I'm trying to work through adding an option that would allow you to prevent Phantoms from spawning in the Bumblezone, but it doesn't seem to work right - despite setting my new option to 'false' in my server's configuration file, I still get occasional Phantoms spawning.

Any ideas on what I'm missing here?

Thanks for any help!

### CODE REVIEW

**Comment by wtchappell** [comment]
I'd like to add one for disabling Endermen potentially, as well.

**Comment by TelepathicGrunt** [comment]
At a cursory glace, the config looks right. Did you restart the game after you change the config value? 

Also, let me know when this is done and I'll change the config to a spawnrate value instead of an on/off switch. That way users can change the frequency of the mob along with turning it off. :)

**Comment by wtchappell** [comment]
I set the value to 'false' in a `bumblezone` config I placed in `defaultconfigs`, and I've confirmed that I can open each individual world's save and see that the file has been copied into `serverconfig` as expected. Sadly, I still get Phantoms spawning - I feel like I'm missing something dumb.

**Comment by wtchappell** [comment]
Is it possible that this check is running before the config is parsed, and it's using the default value every time as a result? I don't really know much about the lifecycle of configuration information relative to when these biomes are set up, but if I add a logging statement here I can see that it's being enabled despite the config file.

**Comment by TelepathicGrunt** [comment]
Alright I did some test and yeah. The issue is that I set the config to be per world so that people can have worlds with different config settings. However, Biomes are registered when you open the game and not when you make or open a world. Even when the config is set to "COMMON" instead of "SERVER", biomes still gets initialized before the config. 

There's no real way around this except moving the logic out of the biome constructor into a mob spawn event which I just did. Check out MobSpawnBehavior class and you'll see the phantom config code there. You can add the other mobs too if you want or whatnot. let me know when you finished with the PR and I'll take it from there. :)

The big downside to moving it to MobSpawnBehavior is I can't control the spawnrate of the mob that well but I'll just blame Forge for how they setup configs lol

**Comment by wtchappell** [comment]
Yup, I thought it was something like that. I've added a knob for Endermen as well, it should be ready whenever you are. :D

**Comment by TelepathicGrunt** [comment]
Thank you! I'll check it out!

**Pull request merged**
