### PR TITLE
Changelog / Documentation Generation

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Separator]: https://raw.githubusercontent.com/ElectronicsArchiver/ElectronicsArchiver/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB/Separator.png

[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｃｏｍｍｅｎｄａｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<div align = center>

![Separator]

<br>
<br>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>

## Draft

Currently still a draft as - depending on when you see this -
I want to refactor my code before it would be merged.

<br>
<br>

## ![Badge Changes]

- Moved -> Split -> Extracted changelog
  data into simple unified format.

- Wrote a small **[Deno]** changelog tool

- Rendered changelog from data

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## Context & Tool Description

I was surpised to find such an extensive changelog,
usually there isn't much substance to be found.

While this is a positive for a potential reader,
it's a pain to format, though since I was happy
to find such a volume of changelog, I wanted to
do it anyways.

As I love to build small tools for jobs like this,
with Deno, I thought this was a perfect fit, which
it is!

The tool is quite simple, it takes the data from
the yaml files and renders it as Markdown.

More specifically, every yaml file is one `Page`,
the name of the file will be the name of the 
Markdown file.

A page contains a list of versions, every version
has three fields that describe it:

`Version` - The version of the project

`Minecraft` - The game version

`Sections` - A table of sections to be rendered

Sections can have arbitrary names and 
contain a list of points to be printed.

Currently a button linked to each sections
header is generated from the `Version` tags,
also every used Minecraft version is linked
to it's Minecraft Wiki page.

The **manual** conversion from the varying data 
found in the orignal changelog files was painful,
but it now allows for near instantanios creation
of the changelog files with whatever changes one
wants.

The tool can be called with:

```sh
deno task changelog
```

It only requires **[Deno]** to be installed,
which is available for all platforms and very
easy to install.

I'm willing and would be happy to write some
docs covering the usage and makeup of the tool,
I haven't done it yet, since it would be a waste
if you didn't merge the PR.

<br>
<br>

## Extra

Not only would I want to contribute additional
work in form of documentation, but I would be 
happy to add further features for formatting
to it, such as icon-syntax, linked usernames
( contributors ), .. whatever you can think
of ..

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out

<br>

[![Button MarkedDown]][MarkedDown]

<br>
<br>

![Separator]

</div>

[Preview]: https://github.com/ElectronicsArchiver/Bumblezone/tree/Documentation-Rework/Documentation/Changelog
[Deno]: https://deno.land/

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
I understand you’re trying to help but I am not looking to over-engineer or add a new tool chain just for a changelog file. This is just a hobby lol. I think other people’s repo would be better suited for these kinds of stuff

**Comment by ElectronicsArchiver** [comment]
It's not a giant toolchain, it's a simple yaml reading, string spitting tool.

I can also make it a GitHub Action that 
automatically runs when a Data file is edited.

> I think other people’s repo would be better suited for these kinds of stuff

I would say, yours is perfect for something like this though,
you have a fuck-ton of changelogs, there is no better place
for something like this than your repository..

**Comment by ElectronicsArchiver** [comment]
It would be a waste not to have your changelog
formatted, considering how difficult it is to
navigate it currently.

Even just considering the generated buttons
that can bring a reader right to the section
they are interested in!

**Comment by TelepathicGrunt** [comment]
This is adding several extra files and a new tool just for changelog which is overkill. And most likely will not look good when posted to curseforge/modrinth.

The way I have my repo and gradle file setup is it takes the content of the changelog.md file, attaches it to my upload and posts it to curseforge and modrinth. On there is where people read the changelog and I formatted my stuff specifically for those sites. Buttons do not help and will not work on those sites and people won’t be reading the changelog here on GitHub anyway. Players only come to GitHub to make issue reports if needed but otherwise, any mod launcher they use will show the changelog from Curseforge/Modrinth site.

When I do a minor version bump, I move the stuff from changelog to changelog_old just as an archive but no longer used. If you wish to see past changelog info of specific versions, please use curseforge or see my older branches for older Mc versions. 

I really do not have any interest in adding another tool just for a changelog file. If the changelog_old file is too much, I’ll just gitignore it and keep it locally on my computer for archiving since my past commits/branches and curseforge/modrinth already have the changelog for every version. You would only need to read the changelog.md file if anything and that’s not going to become ultra big as it’s current content will be archived when I port to 1.19.3 coming around soon

**Comment by ElectronicsArchiver** [comment]
> And most likely will not look good when posted to curseforge/modrinth.

> On there is where people read the changelog and I formatted my stuff specifically for those sites. Buttons do not help and will not work on those sites and people won’t be reading the changelog here on GitHub anyway. Players only come to GitHub to make issue reports if needed but otherwise, any mod launcher they use will show the changelog from Curseforge/Modrinth site.

1. You haven't even tried
2. I can easily switch to shield IO buttons that are just images, so they WILL work.

If you don't want the tool IN your project, you could still make 
use of it though, I could just put it onto one of my orgs.

That way, you would only have the changelog 
markdown files in your repository.

**Comment by TelepathicGrunt** [comment]
Please stop. I already stated my stance. I do not want extra images or buttons in my changelogs. It should just be the changes without any fluff or fancy stuff. Also you will be surprised at how much CurseForge breaks with markdown as their markdown isn’t true markdown. I fought curseforge’s “markdown” a ton already and not looking to do so again lol.

You can try and offer this idea to other people who may be more receptive of this tool. But generally, it’s a good idea to ask someone if they will want a tool or large change before actually making the PR so you don’t waste time if they say no.

Again, sorry but this is not something I want in my workflow nor changelog

**Pull request closed without merging**
